#!/bin/bash
echo Build $DOCKER_TAG
echo Run docker build --build-arg PHP_VERS=$(sed "s/-dev//g" <<< $DOCKER_TAG) -t $IMAGE_NAME .
docker build --build-arg PHP_VERS=$(sed "s/-dev//g" <<< $DOCKER_TAG) -t $IMAGE_NAME .
